// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwvbpjxurmlnxqtmfmcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dmJwanh1cm1sbnhxdG1mbWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDM3MzUsImV4cCI6MjA2MjUxOTczNX0.AJsUPWy9q4Ge0VNDMD_Fg7DVYSRT9AO47cKMPvUm13Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);